# Generated by Django 5.2 on 2025-04-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('sensor_type', models.CharField(max_length=64)),
                ('capabilities', models.JSONField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ha_sensors', to='rooms.room')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ha.sensortemplate')),
            ],
        ),
    ]
