# Generated by Django 5.2 on 2025-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomitemtype_room_grid_size_room_height_room_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='roomitemtype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='room',
            name='pflanzenanzahl',
            field=models.IntegerField(default=0, help_text='Anzahl der Pflanzen im Raum'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('bluetekammer', 'Blütekammer'), ('produktausgabe', 'Produktausgabe'), ('trocknungsraum', 'Trocknungsraum'), ('labor', 'Labor'), ('mutterraum', 'Mutterraum'), ('anzuchtraum', 'Anzuchtraum'), ('verarbeitung', 'Verarbeitung'), ('other', 'Sonstiges')], default='other', max_length=20),
        ),
    ]
