# Generated by Django 5.2.2 on 2025-07-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unifi_device_id',
            field=models.CharField(blank=True, help_text='UniFi Access Device ID für Türzugang', max_length=255, null=True, unique=True),
        ),
    ]
