# Generated by Django 5.2.2 on 2025-07-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_unifi_device_id'),
        ('unifi_protect', '0004_alter_protectsensor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='protect_sensors',
            field=models.ManyToManyField(blank=True, help_text='UniFi Protect Sensoren in diesem Raum', related_name='rooms', to='unifi_protect.protectsensor'),
        ),
    ]
