# Generated by Django 5.2 on 2025-04-16 21:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontonummer', models.CharField(max_length=20, unique=True, verbose_name='Kontonummer')),
                ('name', models.CharField(max_length=255, verbose_name='Kontoname')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo')),
                ('konto_typ', models.CharField(choices=[('AKTIV', 'Aktivkonto'), ('PASSIV', 'Passivkonto'), ('ERTRAG', 'Ertragskonto'), ('AUFWAND', 'Aufwandskonto')], default='AKTIV', max_length=10, verbose_name='Kontotyp')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Bearbeitung'), ('CLOSED', 'Abgeschlossen')], default='OPEN', max_length=20)),
                ('is_retroactive', models.BooleanField(default=False, verbose_name='Rückwirkend angelegt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True, verbose_name='Abschlussnotizen')),
                ('closing_document', models.FileField(blank=True, null=True, upload_to='closings/')),
            ],
            options={
                'verbose_name': 'Geschäftsjahr',
                'verbose_name_plural': 'Geschäftsjahre',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungsnummer', models.CharField(default='TEMP-000', max_length=20, unique=True, verbose_name='Buchungsnummer')),
                ('typ', models.CharField(choices=[('EINZEL', 'Einzelbuchung'), ('MEHRFACH', 'Mehrfachbuchung'), ('MITGLIEDSBEITRAG', 'Mitgliedsbeitragseinzahlung'), ('FOERDERKREDIT', 'Förderkrediteinzahlung')], default='EINZEL', max_length=20, verbose_name='Buchungstyp')),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buchungsdatum')),
                ('is_storno', models.BooleanField(default=False)),
                ('storniert_am', models.DateTimeField(blank=True, null=True)),
                ('verwendungszweck', models.TextField(verbose_name='Verwendungszweck')),
                ('mitgliedsname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mitgliedsname')),
                ('kontostand_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kontostand')),
                ('foerderkredit_stand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Förderkredit-Stand')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Mitglied')),
                ('original_buchung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_versionen', to='buchhaltung.booking')),
                ('storniert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stornobuchungen', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClosingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('adjustment_type', models.CharField(choices=[('DEPRECIATION', 'Abschreibung'), ('PROVISION', 'Rückstellung'), ('ACCRUAL', 'Rechnungsabgrenzung'), ('VALUATION', 'Bewertungskorrektur'), ('OTHER', 'Sonstige')], max_length=20, verbose_name='Typ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_adjustments', to='buchhaltung.booking', verbose_name='Zugehörige Buchung')),
                ('business_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='buchhaltung.businessyear')),
            ],
            options={
                'verbose_name': 'Abschlussbuchung',
                'verbose_name_plural': 'Abschlussbuchungen',
                'ordering': ['business_year', 'adjustment_type'],
            },
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontostand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kontostand')),
                ('foerderkredit_guthaben', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Förderkredit-Guthaben')),
                ('letzte_aktualisierung', models.DateTimeField(auto_now=True, verbose_name='Letzte Aktualisierung')),
                ('mitglied', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Mitglied')),
            ],
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('verwendungszweck', models.TextField(blank=True, null=True, verbose_name='Verwendungszweck')),
                ('laufende_nummer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Laufende Nummer')),
                ('buchungsnummer_sub', models.CharField(blank=True, max_length=30, null=True, verbose_name='Sub-Buchungsnummer')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtransactions', to='buchhaltung.booking')),
                ('haben_konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haben_buchungen', to='buchhaltung.account', verbose_name='Haben-Konto')),
                ('soll_konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soll_buchungen', to='buchhaltung.account', verbose_name='Soll-Konto')),
            ],
        ),
        migrations.CreateModel(
            name='YearClosingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('PREPARATION', 'Vorbereitung'), ('ADJUSTMENTS', 'Abschlussbuchungen'), ('CLOSING', 'Jahresabschluss durchführen'), ('OPENING', 'Neues Jahr eröffnen')], max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Nicht begonnen'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Abgeschlossen'), ('SKIPPED', 'Übersprungen')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closing_steps', to='buchhaltung.businessyear')),
            ],
            options={
                'verbose_name': 'Jahresabschluss-Schritt',
                'verbose_name_plural': 'Jahresabschluss-Schritte',
                'ordering': ['business_year', 'step'],
                'unique_together': {('business_year', 'step')},
            },
        ),
    ]
