# Generated by Django 5.1.6 on 2025-03-09 15:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontonummer', models.CharField(max_length=20, unique=True, verbose_name='Kontonummer')),
                ('name', models.CharField(max_length=255, verbose_name='Kontoname')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo')),
                ('konto_typ', models.CharField(choices=[('AKTIV', 'Aktivkonto'), ('PASSIV', 'Passivkonto'), ('ERTRAG', 'Ertragskonto'), ('AUFWAND', 'Aufwandskonto')], default='AKTIV', max_length=10, verbose_name='Kontotyp')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungsnummer', models.CharField(default='TEMP-000', max_length=20, unique=True, verbose_name='Buchungsnummer')),
                ('typ', models.CharField(choices=[('EINZEL', 'Einzelbuchung'), ('MEHRFACH', 'Mehrfachbuchung')], default='EINZEL', max_length=10, verbose_name='Buchungstyp')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Buchungsdatum')),
                ('verwendungszweck', models.TextField(verbose_name='Verwendungszweck')),
                ('mitglied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Mitglied')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontostand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kontostand')),
                ('foerderkredit_guthaben', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Förderkredit-Guthaben')),
                ('letzte_aktualisierung', models.DateTimeField(auto_now=True, verbose_name='Letzte Aktualisierung')),
                ('mitglied', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Mitglied')),
            ],
        ),
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtransactions', to='buchhaltung.booking')),
                ('haben_konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haben_buchungen', to='buchhaltung.account', verbose_name='Haben-Konto')),
                ('soll_konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soll_buchungen', to='buchhaltung.account', verbose_name='Soll-Konto')),
            ],
        ),
    ]
