# Generated by Django 5.2.2 on 2025-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='foerderkredit_stand',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='foerderkredit_guthaben',
        ),
        migrations.AlterField(
            model_name='booking',
            name='typ',
            field=models.CharField(choices=[('EINZEL', 'Einzelbuchung'), ('MEHRFACH', 'Mehrfachbuchung'), ('MITGLIEDSBEITRAG', 'Mitgliedsbeitragseinzahlung')], default='EINZEL', max_length=20, verbose_name='Buchungstyp'),
        ),
    ]
