# Generated by Django 5.2 on 2025-04-14 18:37

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='foerderkredit_stand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Förderkredit-Stand'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_storno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='kontostand_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kontostand'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mitgliedsname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mitgliedsname'),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='verwendungszweck',
            field=models.TextField(blank=True, null=True, verbose_name='Verwendungszweck'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Buchungsdatum'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='typ',
            field=models.CharField(choices=[('EINZEL', 'Einzelbuchung'), ('MEHRFACH', 'Mehrfachbuchung'), ('MITGLIEDSBEITRAG', 'Mitgliedsbeitragseinzahlung'), ('FOERDERKREDIT', 'Förderkrediteinzahlung')], default='EINZEL', max_length=20, verbose_name='Buchungstyp'),
        ),
    ]
