# Generated by Django 5.2 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0002_booking_foerderkredit_stand_booking_is_storno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='buchungsnummer_sub',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sub-Buchungsnummer'),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='laufende_nummer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Laufende Nummer'),
        ),
    ]
