# Generated by Django 5.2 on 2025-04-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0003_subtransaction_buchungsnummer_sub_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_buchung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_versionen', to='buchhaltung.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='storniert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='storniert_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stornobuchungen', to='members.member'),
        ),
    ]
