# Generated by Django 5.1.6 on 2025-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unifi_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='Benutzer, der das Ereignis ausgelöst hat', max_length=255)),
                ('door', models.CharField(help_text='Tür, an der das Ereignis stattfand', max_length=255)),
                ('event_type', models.CharField(help_text='Typ des Ereignisses (z.B. unlock)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt des Ereignisses')),
            ],
            options={
                'verbose_name': 'Zugriffsereignis',
                'verbose_name_plural': 'Zugriffsereignisse',
                'ordering': ['-timestamp'],
            },
        ),
    ]
