# Generated by Django 5.1.6 on 2025-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='authentication',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
