# Generated by Django 5.2 on 2025-04-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_access', '0003_accessevent_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessevent',
            name='card_uid',
            field=models.CharField(blank=True, help_text='UID der RFID-Karte (falls übermittelt)', max_length=50, null=True),
        ),
    ]
