# Generated by Django 5.2 on 2025-04-16 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=10)),
                ('kontostand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('physical_limitations', models.TextField(blank=True)),
                ('mental_limitations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
