# Generated by Django 5.2 on 2025-04-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modellname')),
                ('beschreibung', models.CharField(blank=True, max_length=255, verbose_name='Kurzbeschreibung')),
                ('alterskategorie', models.CharField(choices=[('18-21', '18–21 Jahre (max. 10\u202f% THC)'), ('21+', '21+ Jahre (über 10\u202f% THC erlaubt)')], default='21+', max_length=5, verbose_name='Alterskategorie')),
                ('produkttyp', models.CharField(choices=[('cannabis', '🌿 Marihuana'), ('haschisch', '🧱 Haschisch'), ('mix', '🔀 Cannabis & Haschisch Mix')], default='cannabis', max_length=15, verbose_name='Produkttyp')),
                ('menge_gramm', models.PositiveIntegerField(verbose_name='Monatsmenge (g)')),
                ('preis_monatlich', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monatlicher Beitrag (€)')),
                ('vermehrungsmaterial', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, verbose_name='Stecklings-Abo')),
                ('preis_vermehrung', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Zusatzpreis Stecklings-Abo (€)')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='mitgliedschaftsmodell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitglieder', to='members.membershipmodel', verbose_name='Mitgliedschaftsmodell'),
        ),
    ]
