# Generated by Django 5.2 on 2025-04-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membershipmodel_member_mitgliedschaftsmodell'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vermehrungsmaterial', models.BooleanField(default=False, verbose_name='Vermehrungsmaterial enthalten')),
                ('stufe', models.CharField(choices=[('Q1', 'Q1 – Basisqualität'), ('Q2', 'Q2 – Mittlere Qualität'), ('Q3', 'Q3 – Premiumqualität')], max_length=2)),
                ('menge_gramm', models.PositiveIntegerField()),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mitgliedsmodell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitaeten', to='members.membershipmodel')),
            ],
        ),
    ]
