# Generated by Django 5.2 on 2025-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_beitragsmodell_member_beitragsmodell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='beitragsmodell',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mitgliedschaftsmodell',
        ),
        migrations.RemoveField(
            model_name='qualitycomponent',
            name='mitgliedsmodell',
        ),
        migrations.DeleteModel(
            name='BeitragsmodellEintrag',
        ),
        migrations.DeleteModel(
            name='Beitragsmodell',
        ),
        migrations.DeleteModel(
            name='MembershipModel',
        ),
        migrations.DeleteModel(
            name='QualityComponent',
        ),
    ]
