# Generated by Django 5.2 on 2025-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='beitrag',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monatlicher Beitrag in Euro', max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('locked', 'Gesperrt'), ('reminder1', '1. Mahnung'), ('reminder2', '2. Mahnung')], default='active', max_length=20),
        ),
    ]
