# Generated by Django 5.2 on 2025-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_beitrag_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age_class',
            field=models.CharField(choices=[('18plus', '18+'), ('21plus', '21+')], default='21plus', max_length=10, verbose_name='Altersklasse'),
        ),
        migrations.AddField(
            model_name='member',
            name='duty_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Geleistete Pflichtstunden'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer'),
        ),
    ]
