# Generated by Django 5.2 on 2025-04-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_age_class_member_duty_hours_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age_class',
        ),
    ]
