# Generated by Django 5.2 on 2025-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_age_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Herr'), ('female', 'Frau'), ('diverse', 'Divers')], default='male', max_length=10, verbose_name='Anrede'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_marginally_employed',
            field=models.BooleanField(default=False, verbose_name='Geringfügig beschäftigt'),
        ),
    ]
