# Generated by Django 5.2 on 2025-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_gender_member_is_marginally_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6, verbose_name='Stundenlohn (€)'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_working_hours',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Maximale Arbeitsstunden'),
        ),
        migrations.AddField(
            model_name='member',
            name='working_hours_per_month',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Arbeitsstunden pro Monat'),
        ),
    ]
