# Generated by Django 5.2.1 on 2025-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='unifi_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
