# Generated by Django 5.2.1 on 2025-05-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_unifi_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='unifi_user_id',
        ),
    ]
