# Generated by Django 5.2 on 2025-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_protect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectsensor',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddIndex(
            model_name='protectsensor',
            index=models.Index(fields=['last_seen'], name='unifi_prote_last_se_1e21e6_idx'),
        ),
        migrations.AddIndex(
            model_name='protectsensor',
            index=models.Index(fields=['name', 'last_seen'], name='unifi_prote_name_cd9ae0_idx'),
        ),
    ]
