# Generated by Django 5.2 on 2025-04-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_protect', '0002_alter_protectsensor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectSensorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='listener', help_text='Datenquelle: listener, api, etc.', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_name', 'timestamp'], name='unifi_prote_sensor__028d0f_idx')],
                'unique_together': {('sensor_name', 'timestamp')},
            },
        ),
    ]
