# Generated by Django 5.2 on 2025-04-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_protect', '0003_protectsensorhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectsensor',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Protect Sensor', 'verbose_name_plural': 'Protect Sensoren'},
        ),
        migrations.AlterModelOptions(
            name='protectsensorhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sensorverlauf', 'verbose_name_plural': 'Sensorverläufe'},
        ),
    ]
