# Generated by Django 5.2 on 2025-04-18 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedPurchase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (SEED_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('manufacturer', models.CharField(help_text='Hersteller/Lieferant der Samen', max_length=255)),
                ('genetics', models.CharField(help_text='Genetische Abstammung', max_length=255)),
                ('strain_name', models.CharField(help_text='Name der Cannabis-Sorte', max_length=255)),
                ('sativa_percentage', models.IntegerField(help_text='Sativa-Anteil in Prozent')),
                ('indica_percentage', models.IntegerField(help_text='Indica-Anteil in Prozent')),
                ('thc_value', models.DecimalField(blank=True, decimal_places=2, help_text='THC-Gehalt laut Hersteller in %', max_digits=5, null=True)),
                ('cbd_value', models.DecimalField(blank=True, decimal_places=2, help_text='CBD-Gehalt laut Hersteller in %', max_digits=5, null=True)),
                ('purchase_date', models.DateField(help_text='Kaufdatum der Samen')),
                ('total_seeds', models.IntegerField(help_text='Anzahl gekaufter Samen')),
                ('remaining_seeds', models.IntegerField(help_text='Anzahl verbleibender Samen')),
                ('image', models.ImageField(blank=True, help_text='Bild der Samen oder Verpackung', null=True, upload_to='seeds/')),
                ('document', models.FileField(blank=True, help_text='Begleitdokumente (Kaufbeleg, Zertifikate, etc.)', null=True, upload_to='seed_docs/')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
            ],
            options={
                'verbose_name': 'Samen-Einkauf',
                'verbose_name_plural': 'Samen-Einkäufe',
                'ordering': ['-purchase_date', 'strain_name'],
            },
        ),
    ]
