# Generated by Django 5.2 on 2025-04-23 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloweringPlantBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowering_plant_batches', to='members.member')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowering_plant_batches', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='FloweringPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_flowering_plants', to='members.member')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='trackandtrace.floweringplantbatch')),
            ],
        ),
        migrations.CreateModel(
            name='MotherPlantBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_plant_batches', to='members.member')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_plant_batches', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='MotherPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_mother_plants', to='members.member')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='trackandtrace.motherplantbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SeedPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('strain_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_seeds', to='members.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_purchases', to='members.member')),
                ('original_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_seeds', to='trackandtrace.seedpurchase')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_purchases', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='motherplantbatch',
            name='seed_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_batches', to='trackandtrace.seedpurchase'),
        ),
        migrations.AddField(
            model_name='floweringplantbatch',
            name='seed_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowering_batches', to='trackandtrace.seedpurchase'),
        ),
    ]
