# Generated by Django 5.2 on 2025-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpurchase',
            name='destroyed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
