# Generated by Django 5.2 on 2025-04-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpurchase',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Raum, in dem die Samen gelagert werden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_purchases', to='rooms.room'),
        ),
    ]
