# Generated by Django 5.2 on 2025-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floweringplant',
            name='destroy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floweringplant',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floweringplant',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='destroy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='destroy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
    ]
