# Generated by Django 5.2 on 2025-04-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0002_floweringplant_destroy_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpurchase',
            name='original_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_seeds', to='trackandtrace.seedpurchase'),
        ),
    ]
