# Generated by Django 5.2 on 2025-04-18 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('trackandtrace', '0002_seedpurchase_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherPlant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (MOTHER_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('planting_date', models.DateField(help_text='Datum der Aussaat')),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung', max_length=255)),
                ('plant_count', models.IntegerField(help_text='Anzahl der gepflanzten Mutterpflanzen')),
                ('remaining_plants', models.IntegerField(help_text='Anzahl der verbleibenden Mutterpflanzen')),
                ('growth_phase', models.CharField(choices=[('seedling', 'Keimling'), ('vegetative', 'Vegetative Phase'), ('mother', 'Mutterpflanze')], default='seedling', help_text='Aktuelle Wachstumsphase', max_length=50)),
                ('growth_medium', models.CharField(blank=True, help_text='Wachstumsmedium (z.B. Erde, Kokos, Hydrokultur)', max_length=255)),
                ('fertilizer', models.CharField(blank=True, help_text='Verwendete Düngemittel', max_length=255)),
                ('light_cycle', models.CharField(blank=True, default='18/6', help_text='Lichtzyklus (z.B. 18/6, 24/0)', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Bild der Mutterpflanzen', null=True, upload_to='mother_plants/')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('seed_source', models.ForeignKey(help_text='Ursprung der Mutterpflanze (Sameneinkauf)', on_delete=django.db.models.deletion.PROTECT, related_name='mother_plants', to='trackandtrace.seedpurchase')),
            ],
            options={
                'verbose_name': 'Mutterpflanze',
                'verbose_name_plural': 'Mutterpflanzen',
                'ordering': ['-planting_date', 'genetic_name'],
            },
        ),
    ]
