# Generated by Django 5.2 on 2025-04-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0003_cuttingbatch_cutting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuttings', to='trackandtrace.cuttingbatch'),
        ),
    ]
