# Generated by Django 5.2 on 2025-04-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0003_seedpurchase_original_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='floweringplantbatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motherplantbatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='floweringplantbatch',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='motherplantbatch',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seedpurchase',
            name='original_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_seeds', to='trackandtrace.seedpurchase'),
        ),
        migrations.AlterField(
            model_name='seedpurchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seedpurchase',
            name='remaining_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
