# Generated by Django 5.2 on 2025-04-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0003_motherplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherplant',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room'),
        ),
    ]
