# Generated by Django 5.2 on 2025-04-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('trackandtrace', '0004_motherplant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherplant',
            name='destroying_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member'),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='destroying_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member'),
        ),
    ]
