# Generated by Django 5.2 on 2025-04-18 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0005_motherplant_destroying_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (CUT_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('cutting_date', models.DateField(help_text='Datum des Schneidens')),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung (von der Mutterpflanze übernommen)', max_length=255)),
                ('cutting_count', models.IntegerField(help_text='Anzahl der geschnittenen Stecklinge')),
                ('remaining_cuttings', models.IntegerField(help_text='Anzahl der verbleibenden Stecklinge')),
                ('growth_phase', models.CharField(choices=[('cutting', 'Frischer Schnitt'), ('rooting', 'Bewurzelung'), ('vegetative', 'Vegetative Phase')], default='cutting', help_text='Aktuelle Wachstumsphase', max_length=50)),
                ('growth_medium', models.CharField(blank=True, help_text='Wachstumsmedium (z.B. Erde, Kokos, Wasser)', max_length=255)),
                ('rooting_agent', models.CharField(blank=True, help_text='Verwendetes Bewurzelungsmittel', max_length=255)),
                ('light_cycle', models.CharField(blank=True, default='18/6', help_text='Lichtzyklus (z.B. 18/6, 24/0)', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Bild der Stecklinge', null=True, upload_to='cuttings/')),
                ('destroying_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member')),
                ('mother_plant_source', models.ForeignKey(help_text='Ursprung der Stecklinge (Mutterpflanze)', on_delete=django.db.models.deletion.PROTECT, related_name='cuttings', to='trackandtrace.motherplant')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('room', models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Steckling',
                'verbose_name_plural': 'Stecklinge',
                'ordering': ['-cutting_date', 'genetic_name'],
            },
        ),
    ]
