# Generated by Django 5.2 on 2025-04-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('trackandtrace', '0005_bloomingcuttingbatch_bloomingcuttingplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_cuttings', to='members.member'),
        ),
        migrations.AddField(
            model_name='cutting',
            name='converted_to',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
