# Generated by Django 5.2 on 2025-05-03 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
        ('trackandtrace', '0006_cutting_converted_at_cutting_converted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blooming_cutting_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='trackandtrace.bloomingcuttingbatch')),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_harvests', to='members.member')),
                ('flowering_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='trackandtrace.floweringplantbatch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='members.member')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='rooms.room')),
            ],
        ),
    ]
