# Generated by Django 5.2 on 2025-04-18 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0006_cutting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cutting',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='transferring_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member'),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='transferring_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member'),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='transferring_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member'),
        ),
        migrations.CreateModel(
            name='FloweringPlant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (FLOWER_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('planting_date', models.DateField(help_text='Datum der Aussaat/Einpflanzung')),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung (übernommen von Quelle)', max_length=255)),
                ('plant_count', models.IntegerField(help_text='Anzahl der gepflanzten Blühpflanzen')),
                ('remaining_plants', models.IntegerField(help_text='Anzahl der verbleibenden Blühpflanzen')),
                ('growth_phase', models.CharField(choices=[('vegetative', 'Vegetative Phase'), ('pre_flower', 'Vorblüte'), ('flowering', 'Blütephase'), ('late_flower', 'Spätblüte'), ('harvest_ready', 'Erntereif')], default='vegetative', help_text='Aktuelle Wachstumsphase', max_length=50)),
                ('growth_medium', models.CharField(blank=True, help_text='Wachstumsmedium (z.B. Erde, Kokos, Hydrokultur)', max_length=255)),
                ('fertilizer', models.CharField(blank=True, help_text='Verwendete Düngemittel', max_length=255)),
                ('light_cycle', models.CharField(blank=True, default='12/12', help_text='Lichtzyklus (z.B. 12/12, 11/13)', max_length=50)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='Erwartetes Erntedatum', null=True)),
                ('image', models.ImageField(blank=True, help_text='Bild der Blühpflanzen', null=True, upload_to='flowering_plants/')),
                ('cutting_source', models.ForeignKey(blank=True, help_text='Ursprung der Blühpflanze (Steckling), wenn aus Steckling', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flowering_plants', to='trackandtrace.cutting')),
                ('destroying_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('room', models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room')),
                ('seed_source', models.ForeignKey(blank=True, help_text='Ursprung der Blühpflanze (Sameneinkauf), wenn direkt aus Samen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flowering_plants', to='trackandtrace.seedpurchase')),
                ('transferring_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member')),
            ],
            options={
                'verbose_name': 'Blühpflanze',
                'verbose_name_plural': 'Blühpflanzen',
                'ordering': ['-planting_date', 'genetic_name'],
            },
        ),
    ]
