# Generated by Django 5.2 on 2025-05-03 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
        ('trackandtrace', '0007_harvestbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_drying_batches', to='members.member')),
                ('harvest_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_batches', to='trackandtrace.harvestbatch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drying_batches', to='members.member')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drying_batches', to='rooms.room')),
            ],
        ),
    ]
