# Generated by Django 5.2 on 2025-04-19 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0007_cutting_is_transferred_cutting_transfer_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (HARVEST_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('harvest_date', models.DateField(help_text='Datum der Ernte')),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung (übernommen von Blühpflanze)', max_length=255)),
                ('plant_count', models.IntegerField(help_text='Anzahl der geernteten Pflanzen')),
                ('fresh_weight', models.DecimalField(decimal_places=2, help_text='Frischgewicht der Ernte in Gramm', max_digits=8)),
                ('remaining_fresh_weight', models.DecimalField(decimal_places=2, help_text='Verbleibendes Frischgewicht in Gramm', max_digits=8)),
                ('flower_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht der Blüten in Gramm', max_digits=8, null=True)),
                ('leaf_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht der Blätter in Gramm', max_digits=8, null=True)),
                ('stem_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht der Stängel in Gramm', max_digits=8, null=True)),
                ('harvest_method', models.CharField(blank=True, help_text='Verwendete Erntemethode', max_length=100)),
                ('expected_drying_date', models.DateField(blank=True, help_text='Erwartetes Datum der Fertigtrocknung', null=True)),
                ('image', models.ImageField(blank=True, help_text='Bild der Ernte', null=True, upload_to='harvests/')),
                ('destroying_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member')),
                ('flowering_plant_source', models.ForeignKey(help_text='Ursprung der Ernte (Blühpflanze)', on_delete=django.db.models.deletion.PROTECT, related_name='harvests', to='trackandtrace.floweringplant')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('room', models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room')),
                ('transferring_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member')),
            ],
            options={
                'verbose_name': 'Ernte',
                'verbose_name_plural': 'Ernten',
                'ordering': ['-harvest_date', 'genetic_name'],
            },
        ),
    ]
