# Generated by Django 5.2 on 2025-04-19 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0008_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutting',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='cutting',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='floweringplant',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='floweringplant',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='harvest',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='seedpurchase',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.CreateModel(
            name='Drying',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_status', models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('last_transfer_date', models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (DRY_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('drying_start_date', models.DateField(help_text='Datum des Trocknungsbeginns')),
                ('drying_end_date', models.DateField(blank=True, help_text='Datum des Trocknungsendes', null=True)),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung (übernommen von Ernte)', max_length=255)),
                ('fresh_weight', models.DecimalField(decimal_places=2, help_text='Frischgewicht in Gramm (übernommen von der Ernte)', max_digits=8)),
                ('dried_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Trockengewicht in Gramm nach Abschluss der Trocknung', max_digits=8, null=True)),
                ('remaining_dried_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Verbleibendes Trockengewicht in Gramm', max_digits=8, null=True)),
                ('drying_method', models.CharField(blank=True, help_text='Verwendete Trocknungsmethode', max_length=100)),
                ('target_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Zielfeuchtigkeitsgehalt in %', max_digits=5, null=True)),
                ('target_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Zieltemperatur während der Trocknung in °C', max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, help_text='Bild der Trocknung', null=True, upload_to='dryings/')),
                ('destroying_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member')),
                ('harvest_source', models.ForeignKey(help_text='Ursprung der Trocknung (Ernte)', on_delete=django.db.models.deletion.PROTECT, related_name='dryings', to='trackandtrace.harvest')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('room', models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room')),
                ('transferring_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member')),
            ],
            options={
                'verbose_name': 'Trocknung',
                'verbose_name_plural': 'Trocknungen',
                'ordering': ['-drying_start_date', 'genetic_name'],
            },
        ),
    ]
