# Generated by Django 5.2 on 2025-05-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0008_dryingbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestbatch',
            name='converted_to_drying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='converted_to_drying_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='drying_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_harvest', to='trackandtrace.dryingbatch'),
        ),
    ]
