# Generated by Django 5.2 on 2025-04-19 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0009_cutting_last_transfer_date_cutting_transfer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_status', models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30)),
                ('is_transferred', models.BooleanField(default=False)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('last_transfer_date', models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True)),
                ('batch_number', models.CharField(help_text='Automatisch generierte Chargennummer (PROC_YYYYMMDD_NNN)', max_length=50, unique=True)),
                ('processing_date', models.DateField(help_text='Datum der Verarbeitung')),
                ('genetic_name', models.CharField(help_text='Genetische Bezeichnung (übernommen von Trocknung)', max_length=255)),
                ('input_weight', models.DecimalField(decimal_places=2, help_text='Eingangsgewicht in Gramm (aus Trocknung)', max_digits=8)),
                ('remaining_weight', models.DecimalField(decimal_places=2, help_text='Verbleibendes Gewicht in Gramm', max_digits=8)),
                ('processing_method', models.CharField(blank=True, help_text='Verwendete Verarbeitungsmethode (z.B. Trimmen, Mahlen, Extraktion)', max_length=100)),
                ('product_type', models.CharField(choices=[('flower', 'Blüte'), ('trim', 'Schnittreste'), ('extract', 'Extrakt'), ('mix', 'Mischung')], default='flower', help_text='Art des erzeugten Produkts', max_length=50)),
                ('flower_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht der verarbeiteten Blüten in Gramm', max_digits=8, null=True)),
                ('trim_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht der Schnittreste in Gramm', max_digits=8, null=True)),
                ('waste_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Gewicht des Abfalls in Gramm', max_digits=8, null=True)),
                ('potency_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Geschätzte Wirkstoffkonzentration in %', max_digits=5, null=True)),
                ('expected_lab_date', models.DateField(blank=True, help_text='Erwartetes Datum der Laborprüfung', null=True)),
                ('image', models.ImageField(blank=True, help_text='Bild der Verarbeitung oder des Endprodukts', null=True, upload_to='processings/')),
                ('destroying_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member')),
                ('drying_source', models.ForeignKey(help_text='Ursprung der Verarbeitung (Trocknung)', on_delete=django.db.models.deletion.PROTECT, related_name='processings', to='trackandtrace.drying')),
                ('responsible_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member')),
                ('room', models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room')),
                ('transferring_member', models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member')),
            ],
            options={
                'verbose_name': 'Verarbeitung',
                'verbose_name_plural': 'Verarbeitungen',
                'ordering': ['-processing_date', 'genetic_name'],
            },
        ),
    ]
