# Generated by Django 5.2 on 2025-05-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0010_processingbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryingbatch',
            name='converted_to_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dryingbatch',
            name='converted_to_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dryingbatch',
            name='processing_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_drying', to='trackandtrace.processingbatch'),
        ),
    ]
