# Generated by Django 5.2 on 2025-05-03 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
        ('trackandtrace', '0011_dryingbatch_converted_to_processing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('input_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sample_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'In Bearbeitung'), ('passed', 'Freigegeben'), ('failed', 'Nicht bestanden')], default='pending', max_length=20)),
                ('thc_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cbd_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lab_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_packaging', models.BooleanField(default=False)),
                ('converted_to_packaging_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_lab_testing_batches', to='members.member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_testing_batches', to='members.member')),
                ('processing_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_testing_batches', to='trackandtrace.processingbatch')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_testing_batches', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_count', models.PositiveIntegerField()),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destroy_reason', models.TextField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_packaging_batches', to='members.member')),
                ('lab_testing_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_batches', to='trackandtrace.labtestingbatch')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_batches', to='members.member')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_batches', to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='labtestingbatch',
            name='packaging_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lab_testing', to='trackandtrace.packagingbatch'),
        ),
    ]
