# Generated by Django 5.2 on 2025-04-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0014_auto_20250420_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedpurchase',
            name='manufacturer_id',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seedpurchase',
            name='manufacturer',
            field=models.ForeignKey(help_text='Hersteller/Lieferant der Samen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seed_purchases', to='trackandtrace.manufacturer'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
