# Generated by Django 5.2.1 on 2025-05-14 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
        ('trackandtrace', '0014_seedpurchase_cbd_percentage_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('distribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_products', to='members.member')),
                ('packaging_units', models.ManyToManyField(related_name='distributions', to='trackandtrace.packagingunit')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_products', to='members.member')),
            ],
        ),
    ]
