# Generated by Django 5.2 on 2025-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0015_remove_seedpurchase_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Ansprechpartner beim Hersteller', max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse des Herstellers', max_length=254),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='order_history',
            field=models.TextField(blank=True, help_text='Bestellhistorie und Informationen'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefonnummer des Herstellers', max_length=50),
        ),
    ]
