# Generated by Django 5.2.1 on 2025-05-19 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0015_productdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpurchase',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_seeds', to='members.member', verbose_name='Verantwortliches Mitglied'),
        ),
    ]
