# Generated by Django 5.2 on 2025-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0016_manufacturer_contact_person_manufacturer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='effect',
            field=models.TextField(blank=True, help_text='Wirkung der Sorte'),
        ),
        migrations.AddField(
            model_name='strain',
            name='flavor',
            field=models.TextField(blank=True, help_text='Geschmack der Sorte'),
        ),
        migrations.AddField(
            model_name='strain',
            name='growing_tips',
            field=models.TextField(blank=True, help_text='Hinweise zur Kultivierung'),
        ),
        migrations.AddField(
            model_name='strain',
            name='height_indoor',
            field=models.PositiveIntegerField(blank=True, help_text='Wuchshöhe Indoor in cm', null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='height_outdoor',
            field=models.PositiveIntegerField(blank=True, help_text='Wuchshöhe Outdoor in cm', null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_type',
            field=models.CharField(choices=[('regular', 'Regulär'), ('feminized', 'Feminisiert'), ('auto', 'Autoflowering'), ('f1', 'F1'), ('f1_hybrid', 'F1 Hybrid'), ('cbd', 'CBD-reich'), ('ruderalis', 'Ruderalis')], default='feminized', help_text='Typ der Cannabissorte', max_length=20),
        ),
        migrations.AddField(
            model_name='strain',
            name='yield_indoor',
            field=models.PositiveIntegerField(blank=True, help_text='Ertrag Indoor in g/m²', null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='yield_outdoor',
            field=models.PositiveIntegerField(blank=True, help_text='Ertrag Outdoor in g/Pflanze', null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='cbd_value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='CBD-Gehalt laut Hersteller in %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='strain',
            name='flowering_time',
            field=models.PositiveIntegerField(blank=True, help_text='Blütezeit in Tagen', null=True),
        ),
    ]
