# Generated by Django 5.2 on 2025-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0017_strain_effect_strain_flavor_strain_growing_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, help_text='Vollständige Anschrift des Herstellers'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse des Ansprechpartners', max_length=254),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='delivery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Übliche Lieferzeit in Tagen', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, help_text='Info-E-Mail-Adresse des Herstellers', max_length=254),
        ),
    ]
