# Generated by Django 5.2.1 on 2025-05-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0017_alter_seedpurchase_responsible_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedpurchase',
            name='responsible_member',
        ),
    ]
