# Generated by Django 5.2 on 2025-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0018_manufacturer_address_manufacturer_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpurchase',
            name='transfer_type',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('mother_plant', 'Als Mutterpflanze übergeführt'), ('flowering_plant', 'Als Blühpflanze übergeführt'), ('mixed', 'Gemischt übergeführt')], default='not_transferred', help_text='Art der Überführung', max_length=30),
        ),
    ]
