# Generated by Django 5.2.1 on 2025-05-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0018_remove_seedpurchase_responsible_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='floweringplant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowering_plants', to='members.member'),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_plants', to='members.member'),
        ),
    ]
