# Generated by Django 5.2.1 on 2025-05-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0019_floweringplant_member_motherplant_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floweringplant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='motherplant',
            name='member',
        ),
    ]
