# Generated by Django 5.2 on 2025-04-20 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('trackandtrace', '0019_seedpurchase_transfer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualCutting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destroying_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_cutting_destructions', to='members.member')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='trackandtrace.cutting')),
            ],
            options={
                'verbose_name': 'Individueller Steckling',
                'verbose_name_plural': 'Individuelle Stecklinge',
            },
        ),
        migrations.CreateModel(
            name='IndividualFloweringPlant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('is_destroyed', models.BooleanField(default=False)),
                ('destruction_reason', models.CharField(blank=True, max_length=255)),
                ('destruction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destroying_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_flowering_destructions', to='members.member')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='trackandtrace.floweringplant')),
            ],
            options={
                'verbose_name': 'Individuelle Blühpflanze',
                'verbose_name_plural': 'Individuelle Blühpflanzen',
            },
        ),
    ]
