# Generated by Django 5.2.2 on 2025-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('rooms', '0004_alter_room_options_alter_roomitemtype_options_and_more'),
        ('trackandtrace', '0020_remove_floweringplant_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingunit',
            options={'ordering': ['-created_at', 'batch_number']},
        ),
        migrations.AddIndex(
            model_name='labtestingbatch',
            index=models.Index(fields=['thc_content'], name='lab_testing_thc_idx'),
        ),
        migrations.AddIndex(
            model_name='labtestingbatch',
            index=models.Index(fields=['processing_batch'], name='lab_testing_processing_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingbatch',
            index=models.Index(fields=['lab_testing_batch'], name='packaging_batch_lab_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingbatch',
            index=models.Index(fields=['batch_number'], name='packaging_batch_number_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingbatch',
            index=models.Index(fields=['-created_at'], name='packaging_batch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['is_destroyed'], name='packaging_unit_available_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['weight'], name='packaging_unit_weight_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['batch'], name='packaging_unit_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['is_destroyed', 'weight'], name='packaging_unit_filters_idx'),
        ),
        migrations.AddIndex(
            model_name='packagingunit',
            index=models.Index(fields=['-created_at'], name='packaging_unit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='processingbatch',
            index=models.Index(fields=['product_type'], name='processing_batch_type_idx'),
        ),
    ]
