# Generated by Django 5.2 on 2025-04-20 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_beitragsmodell_and_more'),
        ('rooms', '0002_remove_room_created_by'),
        ('trackandtrace', '0020_individualcutting_individualfloweringplant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualcutting',
            options={'ordering': ['parent', 'batch_number'], 'verbose_name': 'Individueller Steckling', 'verbose_name_plural': 'Individuelle Stecklinge'},
        ),
        migrations.AlterModelOptions(
            name='individualfloweringplant',
            options={'ordering': ['parent', 'batch_number'], 'verbose_name': 'Individuelle Pflanze', 'verbose_name_plural': 'Individuelle Pflanzen'},
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='cutting_date',
            field=models.DateField(blank=True, help_text='Datum des Schneidens (übernommen vom Eltern-Batch)', null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='genetic_name',
            field=models.CharField(blank=True, help_text='Genetische Bezeichnung (übernommen vom Eltern-Batch)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='growth_medium',
            field=models.CharField(blank=True, help_text='Wachstumsmedium (z.B. Erde, Kokos, Wasser)', max_length=255),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='growth_phase',
            field=models.CharField(choices=[('cutting', 'Frischer Schnitt'), ('rooting', 'Bewurzelung'), ('vegetative', 'Vegetative Phase'), ('transferred', 'Überführt'), ('destroyed', 'Vernichtet')], default='cutting', help_text='Aktuelle Wachstumsphase', max_length=50),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild des individuellen Stecklings', null=True, upload_to='individual_cuttings/'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Gibt an, ob der Steckling noch aktiv ist oder bereits überführt/vernichtet wurde'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='light_cycle',
            field=models.CharField(blank=True, help_text='Lichtzyklus (z.B. 18/6, 24/0)', max_length=50),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='notes',
            field=models.TextField(blank=True, help_text='Individuelle Notizen zu diesem Steckling'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='rooting_agent',
            field=models.CharField(blank=True, help_text='Verwendetes Bewurzelungsmittel', max_length=255),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='transferring_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member'),
        ),
        migrations.AddField(
            model_name='individualcutting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='genetic_name',
            field=models.CharField(blank=True, help_text='Genetische Bezeichnung (übernommen von Eltern-Batch)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='growth_phase',
            field=models.CharField(choices=[('vegetative', 'Vegetative Phase'), ('pre_flower', 'Vorblüte'), ('flowering', 'Blütephase'), ('late_flower', 'Spätblüte'), ('harvest_ready', 'Erntereif'), ('harvested', 'Geerntet'), ('destroyed', 'Vernichtet')], default='vegetative', help_text='Aktuelle Wachstumsphase', max_length=50),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Luftfeuchtigkeit während des Arbeitsschritts in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild der individuellen Pflanze', null=True, upload_to='individual_plants/'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Gibt an, ob die Pflanze noch aktiv ist oder bereits geerntet/vernichtet wurde'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='last_transfer_date',
            field=models.DateTimeField(blank=True, help_text='Datum der letzten Überführung', null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='notes',
            field=models.TextField(blank=True, help_text='Individuelle Notizen zu dieser Pflanze'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='planting_date',
            field=models.DateField(blank=True, help_text='Datum der Aussaat/Einpflanzung (übernommen von Eltern-Batch)', null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Raum, in dem dieser Prozessschritt stattfindet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatur während des Arbeitsschritts in °C', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='transfer_status',
            field=models.CharField(choices=[('not_transferred', 'Nicht übergeführt'), ('partially_transferred', 'Teilweise übergeführt'), ('fully_transferred', 'Vollständig übergeführt')], default='not_transferred', help_text='Überführungsstatus: nicht, teilweise oder vollständig übergeführt', max_length=30),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='transferring_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Überführung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_transfers', to='members.member'),
        ),
        migrations.AddField(
            model_name='individualfloweringplant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cutting',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='drying',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='floweringplant',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='individualcutting',
            name='batch_number',
            field=models.CharField(help_text='Individuelle Stecklingsnummer (CUT_YYYYMMDD_NNN_INDIV_NNN)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='individualcutting',
            name='destroying_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member'),
        ),
        migrations.AlterField(
            model_name='individualcutting',
            name='parent',
            field=models.ForeignKey(help_text='Eltern-Batch dieses individuellen Stecklings', on_delete=django.db.models.deletion.CASCADE, related_name='individual_cuttings', to='trackandtrace.cutting'),
        ),
        migrations.AlterField(
            model_name='individualfloweringplant',
            name='batch_number',
            field=models.CharField(help_text='Individuelle Pflanzennummer (FLOWER_YYYYMMDD_NNN_PLANT_NNN)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='individualfloweringplant',
            name='destroying_member',
            field=models.ForeignKey(blank=True, help_text='Mitglied, das die Vernichtung durchgeführt hat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_destructions', to='members.member'),
        ),
        migrations.AlterField(
            model_name='individualfloweringplant',
            name='parent',
            field=models.ForeignKey(help_text='Eltern-Batch dieser individuellen Pflanze', on_delete=django.db.models.deletion.CASCADE, related_name='individual_plants', to='trackandtrace.floweringplant'),
        ),
        migrations.AlterField(
            model_name='labtesting',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='motherplant',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='processing',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='productdistribution',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='seedpurchase',
            name='responsible_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_responsibilities', to='members.member'),
        ),
    ]
