# Generated by Django 5.2.2 on 2025-06-20 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0021_add_strain_card_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='packaging_images/%Y/%m/', verbose_name='Bild')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packaging_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trackandtrace.packagingbatch')),
            ],
        ),
    ]
