# Generated by Django 5.2.2 on 2025-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0022_packagingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingimage',
            options={'verbose_name': 'Verpackungsbild', 'verbose_name_plural': 'Verpackungsbilder'},
        ),
        migrations.AlterField(
            model_name='packagingimage',
            name='image',
            field=models.ImageField(upload_to='packaging_images/%Y/%m/', verbose_name='Produktbild'),
        ),
    ]
