# Generated by Django 5.2.2 on 2025-06-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0023_alter_packagingimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackagingImage',
        ),
    ]
