# Generated by Django 5.2.2 on 2025-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0024_delete_packagingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingbatch',
            name='price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preis pro Gramm in Euro', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='packagingbatch',
            name='total_batch_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gesamtpreis für diese Verpackung (automatisch berechnet)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='packagingbatch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preis pro Verpackungseinheit (automatisch berechnet)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='packagingunit',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preis für diese Verpackungseinheit in Euro', max_digits=8, null=True),
        ),
    ]
