# Generated by Django 5.2.2 on 2025-06-20 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0025_packagingbatch_price_per_gram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Bild der Verpackung/Produkt', upload_to='trackandtrace/packaging/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optionale Beschreibung des Bildes', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Hauptbild dieser Verpackungscharge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging_batch', models.ForeignKey(help_text='Verpackungscharge zu der dieses Bild gehört', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trackandtrace.packagingbatch')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Mitglied, das das Bild hochgeladen hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_packaging_images', to='members.member')),
            ],
            options={
                'verbose_name': 'Verpackungsbild',
                'verbose_name_plural': 'Verpackungsbilder',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['packaging_batch'], name='packaging_image_batch_idx'), models.Index(fields=['packaging_batch', 'is_primary'], name='packaging_image_primary_idx'), models.Index(fields=['-created_at'], name='packaging_image_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('packaging_batch',), name='unique_primary_packaging_image')],
            },
        ),
    ]
