# Generated by Django 5.2.2 on 2025-06-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0026_packagingimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackagingImage',
        ),
    ]
