# Generated by Django 5.2.2 on 2025-06-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0027_delete_packagingimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdistribution',
            options={'ordering': ['-distribution_date'], 'verbose_name': 'Cannabis-Ausgabe', 'verbose_name_plural': 'Cannabis-Ausgaben'},
        ),
        migrations.AddField(
            model_name='productdistribution',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kontostand nachher'),
        ),
        migrations.AddField(
            model_name='productdistribution',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kontostand vorher'),
        ),
        migrations.AddField(
            model_name='productdistribution',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gesamtpreis'),
        ),
    ]
