# Generated by Django 5.2.2 on 2025-06-24 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0033_floweringplantbatchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestBatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hauptbild', upload_to='trackandtrace/images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatisch generiertes Vorschaubild', null=True, upload_to='trackandtrace/thumbnails/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('harvest_stage', models.CharField(blank=True, choices=[('fresh', 'Frisch geerntet'), ('trimmed', 'Getrimmt'), ('packed', 'Verpackt für Trocknung')], help_text='Stadium der Ernte', max_length=50)),
                ('harvest_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trackandtrace.harvestbatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'verbose_name': 'Ernte-Batch Bild',
                'verbose_name_plural': 'Ernte-Batch Bilder',
                'db_table': 'trackandtrace_harvest_batch_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
