# Generated by Django 5.2.2 on 2025-06-24 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0034_harvestbatchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloomingcuttingbatchimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='bloomingcuttingbatchimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='cuttingbatchimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='cuttingbatchimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='floweringplantbatchimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='floweringplantbatchimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='harvestbatchimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='harvestbatchimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='motherplantbatchimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='motherplantbatchimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='seedpurchaseimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='seedpurchaseimage',
            name='video',
            field=models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='bloomingcuttingbatchimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bloomingcuttingbatchimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='bloomingcuttingbatchimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.AlterField(
            model_name='cuttingbatchimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cuttingbatchimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='cuttingbatchimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.AlterField(
            model_name='floweringplantbatchimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='floweringplantbatchimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='floweringplantbatchimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.AlterField(
            model_name='harvestbatchimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='harvestbatchimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='harvestbatchimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.AlterField(
            model_name='motherplantbatchimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='motherplantbatchimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='motherplantbatchimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.AlterField(
            model_name='seedpurchaseimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='seedpurchaseimage',
            name='image_type',
            field=models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50),
        ),
        migrations.AlterField(
            model_name='seedpurchaseimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member'),
        ),
        migrations.CreateModel(
            name='DryingBatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatisch generiertes Vorschaubild', null=True, upload_to='trackandtrace/thumbnails/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])])),
                ('media_type', models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('drying_stage', models.CharField(blank=True, choices=[('wet', 'Feucht (Tag 1-3)'), ('drying', 'Trocknend (Tag 4-7)'), ('dry', 'Trocken (Tag 8+)'), ('curing', 'Reifend')], help_text='Stadium der Trocknung', max_length=50)),
                ('drying_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trackandtrace.dryingbatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member')),
            ],
            options={
                'verbose_name': 'Trocknungs-Batch Bild/Video',
                'verbose_name_plural': 'Trocknungs-Batch Bilder/Videos',
                'db_table': 'trackandtrace_drying_batch_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
