# Generated by Django 5.2.2 on 2025-06-25 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0038_packagingbatchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Bild-Datei (JPEG, PNG, etc.)', null=True, upload_to='trackandtrace/images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Automatisch generiertes Vorschaubild', null=True, upload_to='trackandtrace/thumbnails/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, help_text='Video-Datei (max. 100MB)', null=True, upload_to='trackandtrace/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])])),
                ('media_type', models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], default='image', editable=False, max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('overview', 'Übersicht'), ('detail', 'Detail'), ('quality', 'Qualitätskontrolle'), ('documentation', 'Dokumentation')], default='overview', help_text='Art/Zweck der Aufnahme', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('documentation_type', models.CharField(blank=True, choices=[('handover', 'Übergabe-Dokumentation'), ('recipient_id', 'Empfänger-Identifikation'), ('product_check', 'Produkt-Überprüfung'), ('signature', 'Unterschrift/Bestätigung'), ('compliance', 'Compliance-Nachweis')], help_text='Art der Dokumentation', max_length=50)),
                ('process_stage', models.CharField(blank=True, choices=[('pre_distribution', 'Vor der Ausgabe'), ('during_distribution', 'Während der Ausgabe'), ('post_distribution', 'Nach der Ausgabe'), ('verification', 'Verifizierung')], help_text='Stadium im Ausgabeprozess', max_length=50)),
                ('retention_days', models.IntegerField(default=90, help_text='Tage bis zur automatischen Löschung (0 = keine automatische Löschung)')),
                ('is_compliance_relevant', models.BooleanField(default=True, help_text='Markiert ob dieses Medium für Compliance relevant ist')),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, help_text='Geplanter Löschzeitpunkt', null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trackandtrace.productdistribution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_%(class)s_media', to='members.member')),
            ],
            options={
                'verbose_name': 'Ausgabe Bild/Video',
                'verbose_name_plural': 'Ausgabe Bilder/Videos',
                'db_table': 'trackandtrace_distribution_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
