# Generated by Django 5.2.2 on 2025-06-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0039_distributionimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistributionImage',
            new_name='ProductDistributionImage',
        ),
    ]
