# Generated by Django 5.2.2 on 2025-07-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0040_rename_distributionimage_productdistributionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDistributionImage',
        ),
    ]
