# Generated by Django 5.2.2 on 2025-07-10 19:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('trackandtrace', '0041_delete_productdistributionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherplant',
            name='is_premium_mother',
            field=models.BooleanField(default=False, help_text='Markiert besonders erfolgreiche Mutterpflanzen'),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='premium_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motherplant',
            name='premium_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_premium_mothers', to='members.member'),
        ),
        migrations.CreateModel(
            name='MotherPlantRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_health', models.IntegerField(help_text='Allgemeine Pflanzengesundheit (1-10 Sterne)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('growth_structure', models.IntegerField(help_text='Wuchsstruktur und Verzweigung (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('growth_notes', models.TextField(blank=True, null=True)),
                ('regeneration_ability', models.IntegerField(help_text='Regenerationsfähigkeit nach Schnitt (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('regeneration_notes', models.TextField(blank=True, null=True)),
                ('regrowth_speed', models.CharField(choices=[('very_fast', 'Sehr schnell (< 7 Tage)'), ('fast', 'Schnell (7-14 Tage)'), ('normal', 'Normal (14-21 Tage)'), ('slow', 'Langsam (> 21 Tage)')], max_length=20)),
                ('regrowth_speed_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('cuttings_harvested', models.PositiveIntegerField(help_text='Anzahl geernteter Stecklinge bei diesem Schnitt')),
                ('cutting_quality', models.IntegerField(help_text='Qualität der Stecklinge (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rooting_success_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Bewurzelungs-Erfolgsquote in %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cutting_batch', models.ForeignKey(blank=True, help_text='Verknüpfung zum zugehörigen Stecklingsschnitt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_rating', to='trackandtrace.cuttingbatch')),
                ('mother_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='trackandtrace.motherplant')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_plant_ratings', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
