# Generated by Django 5.2.1 on 2025-05-09 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannabisStrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Sortenname')),
                ('breeder', models.CharField(max_length=100, verbose_name='Hersteller/Züchter')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('strain_type', models.CharField(choices=[('feminized', 'Feminisiert'), ('regular', 'Regulär'), ('autoflower', 'Autoflower'), ('f1_hybrid', 'F1 Hybrid'), ('cbd', 'CBD-Samen')], default='feminized', max_length=20, verbose_name='Samentyp')),
                ('indica_percentage', models.IntegerField(default=50, help_text='Prozentualer Indica-Anteil (0-100)', verbose_name='Indica-Anteil (%)')),
                ('genetic_origin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Genetische Herkunft')),
                ('flowering_time_min', models.IntegerField(default=50, verbose_name='Blütezeit Minimum (Tage)')),
                ('flowering_time_max', models.IntegerField(default=65, verbose_name='Blütezeit Maximum (Tage)')),
                ('height_indoor_min', models.IntegerField(default=80, verbose_name='Höhe Indoor Minimum (cm)')),
                ('height_indoor_max', models.IntegerField(default=120, verbose_name='Höhe Indoor Maximum (cm)')),
                ('height_outdoor_min', models.IntegerField(blank=True, default=120, null=True, verbose_name='Höhe Outdoor Minimum (cm)')),
                ('height_outdoor_max', models.IntegerField(blank=True, default=180, null=True, verbose_name='Höhe Outdoor Maximum (cm)')),
                ('yield_indoor_min', models.IntegerField(blank=True, default=400, null=True, verbose_name='Ertrag Indoor Minimum (g/m²)')),
                ('yield_indoor_max', models.IntegerField(blank=True, default=500, null=True, verbose_name='Ertrag Indoor Maximum (g/m²)')),
                ('yield_outdoor_min', models.IntegerField(blank=True, default=500, null=True, verbose_name='Ertrag Outdoor Minimum (g/Pflanze)')),
                ('yield_outdoor_max', models.IntegerField(blank=True, default=700, null=True, verbose_name='Ertrag Outdoor Maximum (g/Pflanze)')),
                ('difficulty', models.CharField(choices=[('beginner', 'Anfänger'), ('intermediate', 'Mittel'), ('advanced', 'Fortgeschritten'), ('expert', 'Experte')], default='intermediate', max_length=20, verbose_name='Schwierigkeitsgrad')),
                ('thc_percentage_min', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='THC-Gehalt Minimum (%)')),
                ('thc_percentage_max', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='THC-Gehalt Maximum (%)')),
                ('cbd_percentage_min', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='CBD-Gehalt Minimum (%)')),
                ('cbd_percentage_max', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='CBD-Gehalt Maximum (%)')),
                ('dominant_terpenes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dominante Terpene')),
                ('flavors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geschmacksrichtungen')),
                ('effects', models.CharField(blank=True, max_length=255, null=True, verbose_name='Effekte/Wirkungen')),
                ('general_information', models.TextField(blank=True, null=True, verbose_name='Allgemeine Informationen')),
                ('growing_information', models.TextField(blank=True, null=True, verbose_name='Anbauspezifische Informationen')),
                ('suitable_climate', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('greenhouse', 'Gewächshaus'), ('all', 'Alle')], default='all', max_length=20, verbose_name='Geeignetes Klima')),
                ('growing_method', models.CharField(choices=[('soil', 'Erde'), ('hydro', 'Hydrokultur'), ('coco', 'Kokos'), ('all', 'Alle')], default='all', max_length=20, verbose_name='Anbaumethode')),
                ('resistance_mold', models.IntegerField(default=3, help_text='1 = Sehr anfällig, 5 = Sehr resistent', verbose_name='Schimmelresistenz (1-5)')),
                ('resistance_pests', models.IntegerField(default=3, help_text='1 = Sehr anfällig, 5 = Sehr resistent', verbose_name='Schädlingsresistenz (1-5)')),
                ('resistance_cold', models.IntegerField(default=3, help_text='1 = Sehr anfällig, 5 = Sehr resistent', verbose_name='Kälteresistenz (1-5)')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='Auszeichnungen')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Jahr der Markteinführung')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='Bewertung (1-5)')),
                ('price_per_seed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preis pro Samen (€)')),
                ('seeds_per_pack', models.IntegerField(default=1, verbose_name='Anzahl Samen pro Packung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannabis_strains', to='members.member')),
            ],
            options={
                'verbose_name': 'Cannabis-Sorte',
                'verbose_name_plural': 'Cannabis-Sorten',
            },
        ),
        migrations.CreateModel(
            name='StrainImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='strain_images/%Y/%m/', verbose_name='Bild')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wawi.cannabisstrain')),
            ],
            options={
                'verbose_name': 'Sortenbild',
                'verbose_name_plural': 'Sortenbilder',
            },
        ),
        migrations.CreateModel(
            name='StrainInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Gesamtmenge')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Verfügbare Menge')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Auffüllung')),
                ('strain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='wawi.cannabisstrain')),
            ],
            options={
                'verbose_name': 'Sortenbestand',
                'verbose_name_plural': 'Sortenbestände',
            },
        ),
    ]
