# Generated by Django 5.2.1 on 2025-05-17 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_hourly_wage_member_max_working_hours_and_more'),
        ('wawi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Erstellt'), ('updated', 'Aktualisiert'), ('deactivated', 'Deaktiviert')], default='updated', max_length=20, verbose_name='Aktion')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strain_history', to='members.member')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wawi.cannabisstrain')),
            ],
            options={
                'verbose_name': 'Sortenhistorie',
                'verbose_name_plural': 'Sortenhistorien',
                'ordering': ['-timestamp'],
            },
        ),
    ]
