# Generated by Django 5.2.1 on 2025-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawi', '0002_strainhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='strainhistory',
            name='changes',
            field=models.JSONField(blank=True, null=True, verbose_name='Detaillierte Änderungen'),
        ),
        migrations.AddField(
            model_name='strainhistory',
            name='image_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Bildoperationsdetails'),
        ),
    ]
