# Generated by Django 5.2.1 on 2025-06-04 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_member_unifi_user_id'),
        ('wawi', '0004_strainpricetier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strainpricetier',
            name='in_cultivation',
        ),
        migrations.RemoveField(
            model_name='strainpricetier',
            name='in_flowering',
        ),
        migrations.RemoveField(
            model_name='strainpricetier',
            name='sold_quantity',
        ),
        migrations.AlterField(
            model_name='strainpricetier',
            name='quantity',
            field=models.IntegerField(verbose_name='Menge (Samen pro Packung)'),
        ),
        migrations.AlterField(
            model_name='strainpricetier',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtpreis pro Packung'),
        ),
        migrations.CreateModel(
            name='StrainPurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(verbose_name='Einkaufsdatum')),
                ('quantity', models.IntegerField(verbose_name='Anzahl Packungen')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gesamtkosten')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Lieferant')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='wawi.strainpricetier')),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Eingekauft von')),
            ],
            options={
                'verbose_name': 'Einkaufshistorie',
                'verbose_name_plural': 'Einkaufshistorien',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
