# Generated by Django 5.2.1 on 2025-06-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wawi', '0005_remove_strainpricetier_in_cultivation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrainPurchaseHistory',
        ),
    ]
