# Generated by Django 5.2.1 on 2025-05-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcommand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Befehl', 'verbose_name_plural': 'Befehle'},
        ),
        migrations.AlterModelOptions(
            name='controlparameter',
            options={'ordering': ['control_unit', 'key'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameter'},
        ),
        migrations.AlterModelOptions(
            name='controlschedule',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Zeitplan', 'verbose_name_plural': 'Zeitpläne'},
        ),
        migrations.AlterModelOptions(
            name='controlstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='controlunit',
            options={'ordering': ['room', 'name'], 'verbose_name': 'Steuerungseinheit', 'verbose_name_plural': 'Steuerungseinheiten'},
        ),
    ]
