# Generated by Django 5.2.1 on 2025-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_alter_controlcommand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlunit',
            name='plc_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='plc_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
