# Generated by Django 5.2.1 on 2025-05-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_controlunit_plc_password_controlunit_plc_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlunit',
            name='plc_password',
        ),
        migrations.RemoveField(
            model_name='controlunit',
            name='plc_username',
        ),
    ]
