# Generated by Django 5.2.1 on 2025-05-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_remove_controlunit_plc_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstatus',
            name='led_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlstatus',
            name='output_q0_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='plc_auth_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='plc_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='plc_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='plc_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
