# Generated by Django 5.2.1 on 2025-05-31 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_controlstatus_led_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_plc_address', models.CharField(default='192.168.1.185', help_text='Standard SPS-Adresse', max_length=50)),
                ('default_username', models.CharField(default='sash', help_text='Standard Benutzername', max_length=50)),
                ('default_password', models.CharField(default='Janus72728', help_text='Standard Passwort', max_length=100)),
                ('request_timeout', models.IntegerField(default=5000, help_text='Request Timeout in ms')),
                ('token_refresh_minutes', models.IntegerField(default=55, help_text='Token Refresh vor Ablauf (Minuten)')),
            ],
            options={
                'verbose_name': 'SPS-Konfiguration',
                'verbose_name_plural': 'SPS-Konfiguration',
            },
        ),
        migrations.AddField(
            model_name='controlcommand',
            name='plc_response',
            field=models.JSONField(blank=True, help_text='SPS Antwort', null=True),
        ),
        migrations.AddField(
            model_name='controlunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlstatus',
            name='led_status',
            field=models.BooleanField(default=False, help_text='LED Start/Stopp Status'),
        ),
        migrations.AlterField(
            model_name='controlstatus',
            name='output_q0_status',
            field=models.BooleanField(default=False, help_text='Ausgang Q0 Status'),
        ),
        migrations.AlterField(
            model_name='controlunit',
            name='plc_auth_token',
            field=models.CharField(blank=True, help_text='Aktueller Auth Token', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='controlunit',
            name='plc_password',
            field=models.CharField(blank=True, help_text='SPS API Passwort', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='controlunit',
            name='plc_token_expires',
            field=models.DateTimeField(blank=True, help_text='Token Ablaufzeit', null=True),
        ),
        migrations.AlterField(
            model_name='controlunit',
            name='plc_username',
            field=models.CharField(blank=True, help_text='SPS API Benutzername', max_length=50, null=True),
        ),
    ]
